Pierre/Models/Flavor.cs
using System.Collections.Generic;
namespace Pierre.Models

{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }
    public int FlavorId{get;set;}
    public string Type{get;set;}
    public string Description {get;set;}
    public virtual ApplicationUser User {get;set;}
    public virtual ICollection<FlavorTreat> JoinEntities {get;}
  }
}

Pierre/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Pierre.Models;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;


namespace Pierre.Controllers
{
  public class FlavorsController : Controller
  {
    private readonly PierreContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, PierreContext db)
    {
      _userManager = userManager;
      _db = db;
    }
  [Authorize]
    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors
          .Include(flavor => flavor.JoinEntities)
          .ThenInclude(join => join.Treat)
          .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<ActionResult> DeleteConfirmed(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    [HttpPost]
    public async Task<ActionResult> DeleteTreat(int joinId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult Search (string flavorDescription)
    {
      var thisFlavor = _db.Flavors.Where(flavor => flavor.Description.Contains(flavorDescription)).ToList();
      if(thisFlavor != null){
          return View(thisFlavor);
      }
      else{
        return View("Index");
      }
    }
  }
}

Pierre/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}
@model Pierre.Models.Flavor
<h1>Add a flavor</h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <p>@Html.Label("Flavor Profile")<br>
    @Html.Label("Sweet")
    @Html.RadioButtonFor(model => model.Type, "Sweet")
    @Html.Label("Savory")
    @Html.RadioButtonFor(model => model.Type, "Savory")
    @Html.Label("Spicy")
    @Html.RadioButtonFor(model => model.Type, "Spicy")
    </p>

  <input type="submit" value="Add new flavor" />
}

Pierre/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Pierre/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor;

<h2>Flavor Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>There are no treats that have this flavor</p>
}
else
{
  <h4>Treats of this flavor:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Treat.Name</li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value ="Delete"/>
    }
  }
  </ul>
}
  <p>@Html.ActionLink("Edit Flavor", "Edit")</p>
  <p>@Html.ActionLink("Delete Flavor","Delete")</p> 

Pierre/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Pierre.Models.Flavor

<h2>Edit</h2>

<h4>Edit this Flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)
  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  <input type= "submit" value="Save"/>
}

Pierre/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}
    @using Pierre.Models;

    <h1>Flavors</h1>
    @if (@Model.Count == 0)
    {
      <h3>No Flavors have been added yet!</h3>
    }
    <ul>
      <h3>Savory</h3>
        @foreach (Flavor flavor in Model)
      {
        @if(flavor.Type == "Savory")
      {
        <li>@Html.ActionLink($"{flavor.Description}", "Details", new{id = flavor.FlavorId})</li>

      }
    }
    <h3>Sweet</h3>
    @foreach(Flavor flavor in Model)
    {
      @if(flavor.Type == "Sweet")
      {
        <li>@Html.ActionLink($"{flavor.Description}", "Details", new{id = flavor.FlavorId})</li>
      }
    }
    <h3>Spicy</h3>
    @foreach(Flavor flavor in Model)
    {
      @if(flavor.Type == "Spicy")
      {
        <li>@Html.ActionLink($"{flavor.Description}", "Details", new{id = flavor.FlavorId})</li>
      }
    }
    </ul>
    @using(Html.BeginForm("Search", "Flavors", FormMethod.Post))
    {
      <label>Search for Flavors</label>
      @Html.TextBox("flavorDescription")
      <input type="submit" value="Search">
    }
    @Html.ActionLink("Add a flavor", "Create")

Pierre/Views/Flavors/Search.cshtml
@{
  Layout = "_Layout";
}
@using Pierre.Models;

<h1>Flavors Matching Your Search</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors profiles found!</h3>
} 

<ul>
  @foreach(Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.Description}", "Details", new { id = flavor.FlavorId })</li>
  }
</ul>
<p>@Html.ActionLink("Back to flavors", "Index")</p>